// apps/demo-vue/app/bench/NestedBoxCore.vue
<template>
  <GridLayout v-if="node.depth % 2 === 0 && node.children.length" class="box" columns="*, *" rows="auto, auto">
    <nlabel v-if="showOdd" class="text branch" :text="node.text" textWrap="true" row="0" colSpan="2" />
    <NestedBoxCore v-for="(child, i) in node.children" :key="child.id" :node="child" :show-odd="showOdd" class="cell" row="1" :col="i" />
  </GridLayout>
  <StackLayout v-else class="box">
    <nlabel class="text" :class="node.children.length ? 'branch' : 'leaf'" :text="node.text" textWrap="true" />
    <NestedBoxCore v-for="child in node.children" :key="child.id" :node="child" :show-odd="showOdd" class="cell" />
  </StackLayout>
</template>

<script lang="ts" setup>
import type { NestedNode } from './data';

defineProps<{ node: NestedNode; showOdd: boolean }>();
</script>

<style scoped>
.box {
  padding: 4;
  border-radius: 6;
  background-color: var(--surface);
  border-width: 1;
  border-color: var(--border);
}

.cell {
  margin: 2;
  vertical-alignment: top;
}

.text {
  font-size: 10;
  color: var(--text-2);
  margin: 2;
}

.branch {
  color: var(--muted);
}
</style>

// apps/demo-solid/src/bench/NestedBoxCore.tsx
import { For, Show } from 'solid-js'
import type { NestedNode } from './data'
import './elements'
import './styles'

// cell/row/col stand in for the attrs Vue falls through onto the child component's root.
interface Props {
  node: NestedNode
  showOdd: boolean
  cell?: boolean
  row?: number
  col?: number
}

export default function NestedBoxCore(props: Props) {
  const boxClass = () => (props.cell ? 'nbc-box nbc-cell' : 'nbc-box')

  return (
    <Show
      when={props.node.depth % 2 === 0 && props.node.children.length}
      fallback={
        <stacklayout class={boxClass()} row={props.row} col={props.col}>
          <nlabel class={props.node.children.length ? 'nbc-text nbc-branch' : 'nbc-text nbc-leaf'} text={props.node.text} textWrap={true} />
          <For each={props.node.children}>{(child) => <NestedBoxCore node={child} showOdd={props.showOdd} cell />}</For>
        </stacklayout>
      }
    >
      <gridlayout class={boxClass()} columns="*, *" rows="auto, auto" row={props.row} col={props.col}>
        <Show when={props.showOdd}>
          <nlabel class="nbc-text nbc-branch" text={props.node.text} textWrap={true} row={0} colSpan={2} />
        </Show>
        <For each={props.node.children}>{(child, i) => <NestedBoxCore node={child} showOdd={props.showOdd} cell row={1} col={i()} />}</For>
      </gridlayout>
    </Show>
  )
}
