// apps/demo-solid/src/bench/NestedBoxMason.tsx
import { For, Show } from 'solid-js'
import type { NestedNode } from './data'
import './styles'

// `cell` stands in for the class Vue falls through onto the child component's root.
interface Props {
  node: NestedNode
  showOdd: boolean
  cell?: boolean
}

export default function NestedBoxMason(props: Props) {
  const odd = () => props.node.depth % 2 === 1
  const boxClass = () => `nbm-box ${odd() ? 'nbm-column' : 'nbm-row'}${props.cell ? ' nbm-cell' : ''}`
  const textClass = () => `nbm-text ${props.node.children.length ? 'nbm-branch' : 'nbm-leaf'}${odd() ? '' : ' nbm-full'}`

  return (
    <div class={boxClass()}>
      {/* One array child, so a hidden <p> or a leaf's empty list leaves no "" placeholder text node, which Mason would lay out as an anonymous text run. */}
      {[
        <Show when={props.showOdd || odd()}>
          <p class={textClass()} text={props.node.text} />
        </Show>,
        <For each={props.node.children}>{(child) => <NestedBoxMason node={child} showOdd={props.showOdd} cell />}</For>,
      ]}
    </div>
  )
}

// apps/demo-vue/app/bench/NestedBoxMason.vue
<template>
  <div class="box" :class="node.depth % 2 ? 'column' : 'row'">
    <p v-if="showOdd || node.depth % 2 === 1" class="text" :class="[node.children.length ? 'branch' : 'leaf', node.depth % 2 ? '' : 'full']" :text="node.text" />
    <NestedBoxMason v-for="child in node.children" :key="child.id" :node="child" :show-odd="showOdd" class="cell" />
  </div>
</template>

<script lang="ts" setup>
import type { NestedNode } from './data';

defineProps<{ node: NestedNode; showOdd: boolean }>();
</script>

<style scoped>
.box {
  display: flex;
  gap: 4;
  padding: 4;
  border-radius: 6;
  background-color: var(--surface);
  border-width: 1;
  border-color: var(--border);
}

.row {
  flex-direction: row;
  flex-wrap: wrap;
  align-items: flex-start;
}

.full {
  flex-basis: 100%;
}

.column {
  flex-direction: column;
}

.cell {
  flex-grow: 1;
  flex-basis: 0;
  min-width: 0;
}

.text {
  font-size: 10;
  color: var(--text-2);
}

.branch {
  color: var(--muted);
}
</style>
