// apps/demo-vue/app/plugin-demos/nativescript-masonkit.vue
<template>
  <Page>
    <ActionBar title="nativescript-masonkit">
    </ActionBar>

    <GridLayout>
      <Button class="info" :text="message"/>
    </GridLayout>
  </Page>
</template>

<script lang="ts" setup>
  import { ref } from "nativescript-vue";
  import { DemoSharedNativescriptMasonkit } from '@demo/shared';
  import { } from '@triniwiz/nativescript-masonkit';

  const message = ref("Test nativescript-masonkit");
</script>

<style scoped>

  .info {
    font-size: 20;
    horizontal-align: center;
    vertical-align: center;
  }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-masonkit.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptMasonkit } from '@demo/shared';
import {} from '@triniwiz/nativescript-masonkit';

@Component({
  selector: 'demo-nativescript-masonkit',
  templateUrl: 'nativescript-masonkit.component.html',
})
export class NativescriptMasonkitComponent {
  demoShared: DemoSharedNativescriptMasonkit;

  constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptMasonkit();
  }
}

<ActionBar title="nativescript-masonkit" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-masonkit" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
